apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webhook-manager-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webhook-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webhook-manager-role
subjects:
- kind: ServiceAccount
  name: webhook-manager