---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - climatik.io
  resources:
  - powercappingpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - climatik.io
  resources:
  - powercappingpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - climatik.io
  resources:
  - powercappingpolicies/status
  verbs:
  - get
  - patch
  - update
