---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - powercapping.climatik-project.ai
  resources:
  - powercappingconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - powercapping.climatik-project.ai
  resources:
  - powercappingconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - powercapping.climatik-project.ai
  resources:
  - powercappingconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get