apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: powercappingconfigs.powercapping.climatik-project.ai
spec:
  group: powercapping.climatik-project.ai
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                powerCapLimit:
                  type: integer
                  minimum: 0
                scaleObjectRefs:
                  type: array
                  items:
                    type: object
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      metadata:
                        type: object
                        properties:
                          name:
                            type: string
                        required:
                          - name
                    required:
                      - apiVersion
                      - kind
                      - metadata
              required:
                - powerCapLimit
                - scaleObjectRefs
            status:
              type: object
              properties:
                currentPowerConsumption:
                  type: number
                forecastPowerConsumption:
                  type: number
  scope: Namespaced
  names:
    plural: powercappingconfigs
    singular: powercappingconfig
    kind: PowerCappingConfig
    shortNames:
      - pcc