apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: powercappingconfigs.powercapping.climatik-project.ai
spec:
  group: powercapping.climatik-project.ai
  names:
    kind: PowerCappingConfig
    listKind: PowerCappingConfigList
    plural: powercappingconfigs
    singular: powercappingconfig
    shortNames:
      - gpcc
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                workloadType:
                  type: string
                  enum: ["training", "inference"]
                efficiencyLevel:
                  type: string
                  enum: ["high", "medium", "low"]
                powerCapWatts:
                  type: integer
                temperatureThresholdCelsius:
                  type: integer
                powerCapLimit:
                  type: integer
                scaledObjectRefs:
                  type: array
                  items:
                    type: object
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      metadata:
                        type: object
                        properties:
                          name:
                            type: string
            status:
              type: object
              properties:
                currentPowerConsumption:
                  type: number
                forecastPowerConsumption:
                  type: number