apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: powercappingconfigs.climatik-project.io
spec:
  group: climatik-project.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                workloadType:
                  type: string
                efficiencyLevel:
                  type: string
                powerCappingSpec:
                  type: object
                  properties:
                    kind:
                      type: string
                    absolutePowerCapInWatts:
                      type: object
                      properties:
                        powerCapInWatts:
                          type: integer
                    relativePowerCapInPercentage:
                      type: object
                      properties:
                        powerCapPercentage:
                          type: integer
                        sampleWindow:
                          type: integer
                temperatureThresholdSpec:
                  type: object
                  properties:
                    kind:
                      type: string
                    absoluteTemperatureThresholdInCelsius:
                      type: object
                      properties:
                        temperatureThresholdInCelsius:
                          type: integer
                    relativeTemperatureThresholdInPercentage:
                      type: object
                      properties:
                        temperatureThresholdPercentage:
                          type: integer
                        sampleWindow:
                          type: integer
            status:
              type: object
              properties:
                currentPowerConsumption:
                  type: integer
                forecastPowerConsumption:
                  type: integer
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: powercappingconfigs
    singular: powercappingconfig
    kind: PowerCappingConfig
    shortNames:
    - pcc
