# deployment-stress.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
  namespace: operator-powercapping-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: progrium/stress
        resources:
          limits:
            cpu: "4"  # increased CPU limit to 4
        command: ["stress", "--cpu", "4"]
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"