apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
  namespace: operator-powercapping-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
        powercapping.climatik.io: "high-efficiency-for-stress-powercappingconfig"
    spec:
      containers:
      - name: stress
        image: progrium/stress
        resources:
          limits:
            cpu: "1"  # increased CPU limit to 1
        command: ["sleep", "inf"]
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"