# deployment-llama2-7b.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama2-7b
  namespace: operator-powercapping-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama2-7b
  template:
    metadata:
      labels:
        app: llama2-7b
    spec:
      containers:
      - name: llama2-7b
        image: nginx:latest
        ports:
        - containerPort: 80