apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: llama2-7b-scaleobject
  namespace: operator-powercapping-system
spec:
  scaleTargetRef:
    name: operator-powercapping-controller-manager
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"