apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-powercapping-controller-manager
  namespace: operator-powercapping-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: operator-powercapping-controller-manager
      containers:
      - name: kube-rbac-proxy
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        ports:
        - containerPort: 8443
          name: https
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
      - name: manager
        image: quay.io/climatik-project/climatik-controller:latest
        command: [ "/bin/sh" ]
        args: ["-c", "/manager --metrics-bind-address=127.0.0.1:8080 --leader-elect"]
        ports:
        # - containerPort: 8081
        #   name: healthz
        - containerPort: 8080
          name: metrics
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8081
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 1
        #   periodSeconds: 20
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /readyz
        #     port: 8081
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 1
        #   periodSeconds: 10
        #   failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        env:
          - name: PROMETHEUS_HOST
            value: "http://localhost:9090"
          - name: HIGH_POWER_USAGE_RATIO
            value: "0.95"
          - name: MODERATE_POWER_USAGE_RATIO
            value: "0.8"
          - name: POWER_CAPPING_STRATEGY
            value: "maximize_replicas"
          - name: GITOPS_REPO_URL
            value: "https://github.com/Climatik-Project/Climatik-Project.git"
          - name: GITOPS_REPO_DIR
            value: "/app/climatik-gitops"
          - name: SLACK_WEBHOOK_URL
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: SLACK_WEBHOOK_URL
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: power-capping-operator
  namespace: operator-powercapping-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: power-capping-operator
rules:
- apiGroups: ["climatik-project.io"]
  resources: ["powercappingconfigs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["keda.sh"]
  resources: ["scaledobjects"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: power-capping-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: power-capping-operator
subjects:
- kind: ServiceAccount
  name: power-capping-operator
  namespace: operator-powercapping-system
