apiVersion: powercapping.climatik-project.ai/v1alpha1
kind: PowerCappingConfig
metadata:
  name: example-powercappingconfig
  namespace: operator-powercapping-system
spec:
  workloadType: "training"
  efficiencyLevel: "high"
  powerCapWatts: 1000
  temperatureThresholdCelsius: 75
  powerCapLimit: 1000
  scaledObjectRefs:
    - apiVersion: "keda.sh/v1alpha1"
      kind: "ScaledObject"
      metadata:
        name: "mistral-7b-scaleobject"
    - apiVersion: "keda.sh/v1alpha1"
      kind: "ScaledObject"
      metadata:
        name: "llama2-7b-scaleobject"
    - apiVersion: "keda.sh/v1alpha1"
      kind: "ScaledObject"
      metadata:
        name: "stress-scaleobject"