name: Auto Create PR and Merge on Format Check

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  createPR:
    runs-on: ubuntu-latest
    outputs:
      pull_request_number: ${{ steps.create_pr.outputs.pull_request_number }}
    steps:
      - name: Check if actor is trusted
        id: check_trusted
        env:
          TRUSTED_CONTRIBUTORS: ${{ secrets.TRUSTED_CONTRIBUTORS }}
        run: |
          if echo "${TRUSTED_CONTRIBUTORS}" | grep -wq "${{ github.actor }}"; then
            echo "IS_TRUSTED=true" >> $GITHUB_ENV
          else
            echo "IS_TRUSTED=false" >> $GITHUB_ENV
          fi

      - name: Checkout code
        if: env.IS_TRUSTED == 'true'
        uses: actions/checkout@v4

      - name: Get last commit title and message
        if: env.IS_TRUSTED == 'true'
        id: commit
        run: |
          echo "title=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "message=$(git log -1 --pretty=%b)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: env.IS_TRUSTED == 'true'
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "${{ steps.commit.outputs.title }}"
          pr_body: "${{ steps.commit.outputs.message }}"

      - name: Debug - Print Pull Request Number
        if: env.IS_TRUSTED == 'true'
        run: echo "Pull Request Number - ${{ steps.create_pr.outputs.pull_request_number }}"

  formatCheck:
    needs: createPR
    if: needs.createPR.outputs.pull_request_number
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Print Pull Request Number
        run: echo "Pull Request Number - ${{ needs.createPR.outputs.pull_request_number }}"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ needs.createPR.outputs.pull_request_number }}/head

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest yapf

      - name: Check format with YAPF
        run: |
          STYLE="pep8"
          yapf --diff --recursive --style=$STYLE src || {
            echo "Some Python files do not conform to the $STYLE style."
            echo "Please run YAPF on your changes with the $STYLE style and update the PR."
            exit 1
          }

  mergePR:
    needs: [createPR, formatCheck]
    if: needs.createPR.outputs.pull_request_number && needs.formatCheck.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Print Pull Request Number
        run: echo "Pull Request Number - ${{ needs.createPR.outputs.pull_request_number }}"

      - name: Debug - Print Format Check Result
        run: echo "Format Check Result - ${{ needs.formatCheck.result }}"

      - name: Automatically merge PR
        uses: pascalgn/automerge-action@58724c982461efbb7865b3762d7bff0d4756f57a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          PULL_REQUEST: ${{ needs.createPR.outputs.pull_request_number }}