name: Auto Create PR on Push

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Check if actor is trusted
        id: check_trusted
        run: echo "IS_TRUSTED=$(echo ${{ fromJson(github.secrets.TRUSTED_CONTRIBUTORS) }} | grep -wq ${{ github.actor }} && echo 'true' || echo 'false')" >> $GITHUB_ENV

      - name: Checkout code
        if: env.IS_TRUSTED == 'true'
        uses: actions/checkout@v2

      - name: Get last commit title and message
        if: env.IS_TRUSTED == 'true'
        id: commit
        run: |
          echo "::set-output name=title::$(git log -1 --pretty=%s)"
          echo "::set-output name=message::$(git log -1 --pretty=%b)"

      - name: Create Pull Request
        if: env.IS_TRUSTED == 'true'
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "${{ steps.commit.outputs.title }}"
          pr_body: "${{ steps.commit.outputs.message }}"
          pr_label: "automerge"
