name: Auto Create and Merge PR

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  createAndMergePR:
    runs-on: ubuntu-latest
    steps:
      - name: Check if actor is trusted
        id: check_trusted
        env:
          TRUSTED_CONTRIBUTORS: ${{ secrets.TRUSTED_CONTRIBUTORS }}
        run: |
          if echo "${TRUSTED_CONTRIBUTORS}" | grep -wq "${{ github.actor }}"; then
            echo "IS_TRUSTED=true" >> $GITHUB_ENV
          else
            echo "IS_TRUSTED=false" >> $GITHUB_ENV
          fi

      - name: Checkout code
        if: env.IS_TRUSTED == 'true'
        uses: actions/checkout@v2

      - name: Get last commit title and message
        if: env.IS_TRUSTED == 'true'
        id: commit
        run: |
          echo "::set-output name=title::$(git log -1 --pretty=%s)"
          echo "::set-output name=message::$(git log -1 --pretty=%b)"

      - name: Create Pull Request
        if: env.IS_TRUSTED == 'true'
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "${{ steps.commit.outputs.title }}"
          pr_body: "${{ steps.commit.outputs.message }}"
          pr_label: "automerge"

      - name: Automatically merge PR
        if: env.IS_TRUSTED == 'true' && steps.create_pr.outputs.pr_number
        uses: pascalgn/automerge-action@58724c982461efbb7865b3762d7bff0d4756f57a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          PULL_REQUEST: ${{ steps.create_pr.outputs.pr_number }}