# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Format Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]

jobs:
  formatCheck:
    if: startsWith(github.head_ref, 'auto-pr-') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest yapf

      - name: Check format with YAPF
        run: |
          STYLE="pep8"
          yapf --diff --recursive --style=$STYLE src || {
            echo "Some Python files do not conform to the $STYLE style."
            echo "Please run YAPF on your changes with the $STYLE style and update the PR."
            exit 1
          }