name: Format Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]

jobs:
  formatCheck:
    if: startsWith(github.ref, 'refs/heads/auto-pr-') == false && !contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Check if actor is trusted
        id: check_trusted
        env:
          TRUSTED_CONTRIBUTORS: ${{ secrets.TRUSTED_CONTRIBUTORS }}
        run: |
          if echo "${TRUSTED_CONTRIBUTORS}" | grep -wq "${{ github.actor }}"; then
            echo "IS_TRUSTED=true" >> $GITHUB_ENV
          else
            echo "IS_TRUSTED=false" >> $GITHUB_ENV
          fi

      - name: Checkout code
        if: env.IS_TRUSTED == 'false'
        uses: actions/checkout@v4

      - name: Set up Python
        if: env.IS_TRUSTED == 'false'
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        if: env.IS_TRUSTED == 'false'
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest yapf

      - name: Check format with YAPF
        if: env.IS_TRUSTED == 'false'
        run: |
          STYLE="pep8"
          yapf --diff --recursive --style=$STYLE src || {
            echo "Some Python files do not conform to the $STYLE style."
            echo "Please run YAPF on your changes with the $STYLE style and update the PR."
            exit 1
          }